users/applications/home/urls.py
from django.urls import path

from . import views

app_name = "home_app"

urlpatterns = [
    path(
        'user-panel/',
        views.HomePage.as_view(),
        name='panel'),
    
]

users/applications/users/urls.py
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path(
        'register/',
        views.UserRegisterView.as_view(),
        name='user-register'),
    path(
        'login/',
        views.Login.as_view(),
        name='user-login'),
    path(
        'logout/',
        views.Logout.as_view(),
        name='user-logout'),
    
]

users/users/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('applications.users.urls')),
    path('home/', include('applications.home.urls'))
]

users/applications/home/models.py
from django.db import models

# Create your models here.

users/applications/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin

from .managers import UserManager

class User(AbstractBaseUser, PermissionsMixin):

    gender_choices = [
        ['M', 'Masculino'],
        ['F', 'Femenino'],
        ['O', 'Otro']
    ]

    username = models.CharField("Username", max_length=10, unique=True)
    email = models.EmailField()
    nombres = models.CharField(max_length=40, blank=True)
    apellidos = models.CharField(max_length=40, blank=True)
    genero = models.CharField("Genero", max_length=1, choices=gender_choices, blank=True)
    #
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'username'

    REQUIRED_FIELDS = [
        'email',
    ]

    objects = UserManager()

    def get_short_name(self):
        return self.username
    
    def get_full_name(self):
        return f'{self.nombres} {self.apellidos}'
    
    def __str__(self):
        return f'{self.id}-{self.username}'

    
    

users/applications/users/forms.py
from django import forms

from .models import User

class UserRegisterForm(forms.ModelForm):

    password1 = forms.CharField(
        label = 'Contraseña',
        required = True,
        widget = forms.PasswordInput(
            attrs = {
                'placeholder': 'Contraseña'
            }
        )
    )
    password2 = forms.CharField(
        label = 'Repetir contraseña',
        required = True,
        widget = forms.PasswordInput(
            attrs = {
                'placeholder': 'Repetir contraseña'
            }
        )
    )

    class Meta:
        model = User
        fields = ('__all__')
        fields = [
            'username',
            'email',
            'nombres',
            'apellidos',
            'genero',
        ]
    
    def clean_password2(self):
        if self.cleaned_data['password1'] != self.cleaned_data['password2']:
            self.add_error('password2', 'las pw son distintas')
        else:
            if len(self.cleaned_data['password1']) <= 5:
                self.add_error('password1', 'la contraseña debe tener +5 caracteres')


class LoginForm(forms.Form):    
    username = forms.CharField(
        label = 'Username',
        required = True,
        widget = forms.TextInput(
            attrs = {
                'placeholder': 'Contraseña'
            }
        )
    )
    password = forms.CharField(
        label = 'Contraseña',
        required = True,
        widget = forms.PasswordInput(
            attrs = {
                'placeholder': 'Contraseña'
            }
        )
    )

users/applications/home/views.py
from django.shortcuts import render

from django.views.generic import (
    TemplateView
)

# Create your views here.


class HomePage(TemplateView):
    template_name = 'home/index.html'

users/applications/users/views.py
from django.shortcuts import render
from django.views.generic import (
    View,
    CreateView
)
from django.views.generic.edit import (
    FormView
)
from django.urls import reverse_lazy, reverse
from .forms import UserRegisterForm, LoginForm
from .models import User
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
# Create your views here.

class UserRegisterView(FormView):
    template_name = 'users/register.html'
    form_class = UserRegisterForm
    success_url = '.'

    def form_valid(self, form):
        User.objects.create_user(
            form.cleaned_data['username'],
            form.cleaned_data['email'],
            form.cleaned_data['password1'],
            nombres = form.cleaned_data['nombres'],
            apellidos = form.cleaned_data['apellidos'],
            genero = form.cleaned_data['genero'],
        )

        return super(UserRegisterView, self).form_valid(form)

class Login(FormView):
    template_name = 'users/login.html'
    form_class = LoginForm
    success_url = reverse_lazy('home_app:panel')

    def form_valid(self, form):

        user = authenticate(
            username = form.cleaned_data['username'],
            password = form.cleaned_data['password']
        )
        login(self.request, user)

        return super(Login, self).form_valid(form)
    
class Logout(View):
    def get(self, request, *args, **kwargs):
        logout(request)

        return HttpResponseRedirect(
            reverse(
                'users_app:user-login'
            )
        )

users/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Panel de usuario</h1>
    <h3>Bienvenido: </h3>
    <ul>
        <li><a href="{% url 'users_app:user-logout' %}">Cerrar sesion</a></li>
        <li><a href="#">Actualizar datos</a></li>
    </ul>
</body>
</html>

users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Acceder al sistema</h1>
    <form method="POST"> {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Login</button>
    </form>
</body>
</html>

users/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Registrar nuevo usuario</h1>
    <form method="POST"> {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</body>
</html>